apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: statusreconciler.community.tanzu.vmware.com.0.1.0
spec:
  refName: statusreconciler.community.tanzu.vmware.com
  version: 0.1.0
  releaseNotes: "status reconciler release"
  licenses:
    - "UNKNOWN"
  template:
    spec:
      fetch:
        - imgpkgBundle:
            image: # Get this value by pushing to your OCI Registry
      template:
        - ytt:
            paths:
              - config/
        - kbld:
            paths:
              - "-"
              - .imgpkg/images.yml
      deploy:
        - kapp: {}
