apiVersion: data.packaging.carvel.dev/v1alpha1
kind: PackageMetadata
metadata:
  name: prow-cm.community.tanzu.vmware.com
spec:
  displayName: "prow-cm"
  longDescription: ""
  shortDescription: ""
  providerName: VMware
  maintainers:
    - name: ""
  categories:
    - ""
