apiVersion: data.packaging.carvel.dev/v1alpha1
kind: PackageMetadata
metadata:
  name: prow-cm.community.tanzu.vmware.com
spec:
  displayName: "prow-cm"
  longDescription: "Prow Controller Manager"
  shortDescription: "PROW Controller Manager"
  providerName: VMware
  maintainers:
    - name: "Hackapalooza"
  categories:
    - "ci"
