apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: deck.prow.plugin.0.1.0
spec:
  refName: deck.prow.plugin
  version: 0.1.0
  releaseNotes: "relevant release notes..."
  licenses:
    - "UNKNOWN"
  template:
    spec:
      fetch:
        - imgpkgBundle:
            image: public.ecr.aws/t0q8k6g2/prow-plugin/deck@sha256:d505c02eed1f29acea0c487337a357cbecf2b34644e98cacdaa240217e4f8be2
      template:
        - ytt:
            paths:
              - config/
        - kbld:
            paths:
              - "-"
              - .imgpkg/images.yml
      deploy:
        - kapp: {}
