apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: deck.community.tanzu.vmware.com.0.1.0
spec:
  refName: deck.community.tanzu.vmware.com
  version: 0.1.0
  releaseNotes: "relevant release notes..."
  licenses:
    - "UNKNOWN"
  template:
    spec:
      fetch:
        - imgpkgBundle:
            image: public.ecr.aws/t0q8k6g2/prow-plugin/deck@sha256:6482e2e473b69240e98f063948576f8bcccf4689d8e653b0c84df9909baa9f33
      template:
        - ytt:
            paths:
              - config/
        - kbld:
            paths:
              - "-"
              - .imgpkg/images.yml
      deploy:
        - kapp: {}
