apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: ghproxy.prow.plugin.0.1.0
spec:
  refName: ghproxy.prow.plugin
  version: 0.1.0
  releaseNotes: "relevant release notes..."
  licenses:
    - "UNKNOWN"
  template:
    spec:
      fetch:
        - imgpkgBundle:
            image: public.ecr.aws/t0q8k6g2/prow-plugin/ghproxy@sha256:db4146b89746b3f46e35ae0e2ac61a8883d9b2b6e0ddc49d49f7a3e0c87d05b9
      template:
        - ytt:
            paths:
              - config/
        - kbld:
            paths:
              - "-"
              - .imgpkg/images.yml
      deploy:
        - kapp: {}
