apiVersion: data.packaging.carvel.dev/v1alpha1
kind: PackageMetadata
metadata:
  name: tide.community.tanzu.vmware.com
spec:
  displayName: "tide"
  longDescription: "PROW tide"
  shortDescription: "PROW tide"
  providerName: VMware
  maintainers:
    - name: "Hackapalooza"
  categories:
    - "ci"
