apiVersion: data.packaging.carvel.dev/v1alpha1
kind: PackageMetadata
metadata:
  name: hook.prow.plugin
spec:
  displayName: "hook"
  longDescription: ""
  shortDescription: ""
  providerName: VMware
  maintainers:
    - name: ""
  categories:
    - ""
