---
apiVersion: data.packaging.carvel.dev/v1alpha1
kind: PackageMetadata
metadata:
  name: deck.prow.plugin
spec:
  displayName: "deck"
  longDescription: ""
  shortDescription: ""
  providerName: VMware
  maintainers:
    - name: ""
  categories:
    - ""
---
apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: deck.prow.plugin.0.1.0
spec:
  refName: deck.prow.plugin
  version: 0.1.0
  releaseNotes: "relevant release notes..."
  licenses:
    - "UNKNOWN"
  template:
    spec:
      fetch:
        - imgpkgBundle:
            image: public.ecr.aws/t0q8k6g2/prow-plugin/deck@sha256:d505c02eed1f29acea0c487337a357cbecf2b34644e98cacdaa240217e4f8be2
      template:
        - ytt:
            paths:
              - config/
        - kbld:
            paths:
              - "-"
              - .imgpkg/images.yml
      deploy:
        - kapp: {}
---
apiVersion: data.packaging.carvel.dev/v1alpha1
kind: PackageMetadata
metadata:
  name: crier.prow.plugin
spec:
  displayName: "crier"
  longDescription: "Prow Component"
  shortDescription: "prow component"
  providerName: VMware
  maintainers:
    - name: Rajas Kakodkar
  categories:
    - "prow"
---
apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: crier.prow.plugin.0.1.0
spec:
  refName: crier.prow.plugin
  version: 0.1.0
  releaseNotes: "crier https://github.com/kubernetes/test-infra"
  valuesSchema:
    openAPIv3:
      title: crier.prow.plugin.0.1.0 values schema
      properties:
        namespace:
          type: string
          description: The namespace in which to deploy crier.
          default: prow
          examples:
            - custom-namespace
  licenses:
    - "Apache 2.0"
  template:
    spec:
      fetch:
        - imgpkgBundle:
            image: public.ecr.aws/t0q8k6g2/prow-plugin/crier@sha256:2401e35b3ce3fd321f54d41462be2b2c3c367d7d039455648010f008f1d98930
      template:
        - ytt:
            paths:
              - config/
        - kbld:
            paths:
              - "-"
              - .imgpkg/images.yml
      deploy:
        - kapp: {}

---
apiVersion: data.packaging.carvel.dev/v1alpha1
kind: PackageMetadata
metadata:
  name: horologium.prow.plugin
spec:
  displayName: "horologium"
  longDescription: ""
  shortDescription: ""
  providerName: VMware
  maintainers:
    - name: ""
  categories:
    - ""
---
apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: horologium.prow.plugin.0.1.0
spec:
  refName: horologium.prow.plugin
  version: 0.1.0
  releaseNotes: "relevant release notes..."
  licenses:
    - "UNKNOWN"
  template:
    spec:
      fetch:
        - imgpkgBundle:
            image: public.ecr.aws/t0q8k6g2/prow-plugin/horologium@sha256:f470c56f35322df476ced88c3d3f525f984b411d996fb7a250dbb99d86e353ae
      template:
        - ytt:
            paths:
              - config/
        - kbld:
            paths:
              - "-"
              - .imgpkg/images.yml
      deploy:
        - kapp: {}
---
apiVersion: data.packaging.carvel.dev/v1alpha1
kind: PackageMetadata
metadata:
  name: prow-cm.prow.plugin
spec:
  displayName: "prow-cm"
  longDescription: "Prow Controller Manager"
  shortDescription: "PROW Controller Manager"
  providerName: VMware
  maintainers:
    - name: "Hackapalooza"
  categories:
    - "ci"
---
apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: prow-cm.prow.plugin.0.1.0
spec:
  refName: prow-cm.prow.plugin
  version: 0.1.0
  releaseNotes: "relevant release notes..."
  licenses:
    - "UNKNOWN"
  template:
    spec:
      fetch:
        - imgpkgBundle:
            image: public.ecr.aws/t0q8k6g2/prow-plugin/prow-cm@sha256:7ac2812d3aba3ff6affa1cb383d68889c0e54d1c0a9b3c7e00ee03ebe5e91768
      template:
        - ytt:
            paths:
              - config/
        - kbld:
            paths:
              - "-"
              - .imgpkg/images.yml
      deploy:
        - kapp: {}
---
apiVersion: data.packaging.carvel.dev/v1alpha1
kind: PackageMetadata
metadata:
  name: sinker.prow.plugin
spec:
  displayName: "sinker"
  longDescription: "PROW Sinker"
  shortDescription: "PROW Sinker"
  providerName: VMware
  maintainers:
    - name: "Hackapalooza"
  categories:
    - "ci"
---
apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: sinker.prow.plugin.0.1.0
spec:
  refName: sinker.prow.plugin
  version: 0.1.0
  releaseNotes: "relevant release notes..."
  licenses:
    - "UNKNOWN"
  template:
    spec:
      fetch:
        - imgpkgBundle:
            image: public.ecr.aws/t0q8k6g2/prow-plugin/sinker@sha256:d46ccdff7265c7f6d0ed3626b758c739bf76c11ee8f8505fcca88e9945b59fd8
      template:
        - ytt:
            paths:
              - config/
        - kbld:
            paths:
              - "-"
              - .imgpkg/images.yml
      deploy:
        - kapp: {}
---
apiVersion: data.packaging.carvel.dev/v1alpha1
kind: PackageMetadata
metadata:
  name: statusreconciler.prow.plugin
spec:
  displayName: "statusreconciler"
  longDescription: "PROW Status Reconciler"
  shortDescription: "PROW Status Reconciler"
  providerName: VMware
  maintainers:
    - name: "Hackapalooza"
  categories:
    - "ci"
---
apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: statusreconciler.prow.plugin.0.1.0
spec:
  refName: statusreconciler.prow.plugin
  version: 0.1.0
  releaseNotes: "status reconciler release"
  licenses:
    - "UNKNOWN"
  template:
    spec:
      fetch:
        - imgpkgBundle:
            image: public.ecr.aws/t0q8k6g2/prow-plugin/statusreconciler@sha256:3b5e7e682892ef12ba6685183557bdbace8b09ecb3a400881217aa436e802491
      template:
        - ytt:
            paths:
              - config/
        - kbld:
            paths:
              - "-"
              - .imgpkg/images.yml
      deploy:
        - kapp: {}
---
apiVersion: data.packaging.carvel.dev/v1alpha1
kind: PackageMetadata
metadata:
  name: tide.prow.plugin
spec:
  displayName: "tide"
  longDescription: "PROW tide"
  shortDescription: "PROW tide"
  providerName: VMware
  maintainers:
    - name: "Hackapalooza"
  categories:
    - "ci"
---
apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: tide.prow.plugin.0.1.0
spec:
  refName: tide.prow.plugin
  version: 0.1.0
  releaseNotes: "tide release"
  licenses:
    - "UNKNOWN"
  template:
    spec:
      fetch:
        - imgpkgBundle:
            image: public.ecr.aws/t0q8k6g2/prow-plugin/tide@sha256:91c410753f17a8bd87c0d9b646d295df86110225b5e3dc86ad24a12586564849
      template:
        - ytt:
            paths:
              - config/
        - kbld:
            paths:
              - "-"
              - .imgpkg/images.yml
      deploy:
        - kapp: {}
---
apiVersion: data.packaging.carvel.dev/v1alpha1
kind: PackageMetadata
metadata:
  name: hook.prow.plugin
spec:
  displayName: "hook"
  longDescription: ""
  shortDescription: ""
  providerName: VMware
  maintainers:
    - name: ""
  categories:
    - ""
---
apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: hook.prow.plugin.0.1.0
spec:
  refName: hook.prow.plugin
  version: 0.1.0
  releaseNotes: "relevant release notes..."
  licenses:
    - "UNKNOWN"
  template:
    spec:
      fetch:
        - imgpkgBundle:
            image: public.ecr.aws/t0q8k6g2/prow-plugin/hook@sha256:632391aa30bbcbf20223c8678e712473f236df8c6740ea758fe7973ba8f084fd
      template:
        - ytt:
            paths:
              - config/
        - kbld:
            paths:
              - "-"
              - .imgpkg/images.yml
      deploy:
        - kapp: {}
---
apiVersion: data.packaging.carvel.dev/v1alpha1
kind: PackageMetadata
metadata:
  name: ghproxy.prow.plugin
spec:
  displayName: "ghproxy"
  longDescription: ""
  shortDescription: ""
  providerName: VMware
  maintainers:
    - name: ""
  categories:
    - ""
---
apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: ghproxy.prow.plugin.0.1.0
spec:
  refName: ghproxy.prow.plugin
  version: 0.1.0
  releaseNotes: "relevant release notes..."
  licenses:
    - "UNKNOWN"
  template:
    spec:
      fetch:
        - imgpkgBundle:
            image: public.ecr.aws/t0q8k6g2/prow-plugin/ghproxy@sha256:db4146b89746b3f46e35ae0e2ac61a8883d9b2b6e0ddc49d49f7a3e0c87d05b9
      template:
        - ytt:
            paths:
              - config/
        - kbld:
            paths:
              - "-"
              - .imgpkg/images.yml
      deploy:
        - kapp: {}
