apiVersion: data.packaging.carvel.dev/v1alpha1
kind: PackageMetadata
metadata:
  name: statusreconciler.community.tanzu.vmware.com
spec:
  displayName: "statusreconciler"
  longDescription: "PROW Status Reconciler"
  shortDescription: "PROW Status Reconciler"
  providerName: VMware
  maintainers:
    - name: "Hackapalooza"
  categories:
    - "ci"
