apiVersion: data.packaging.carvel.dev/v1alpha1
kind: PackageMetadata
metadata:
  name: sinker.prow.plugin
spec:
  displayName: "sinker"
  longDescription: "PROW Sinker"
  shortDescription: "PROW Sinker"
  providerName: VMware
  maintainers:
    - name: "Hackapalooza"
  categories:
    - "ci"
