apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: hook.prow.plugin.0.1.0
spec:
  refName: hook.prow.plugin
  version: 0.1.0
  releaseNotes: "relevant release notes..."
  licenses:
    - "UNKNOWN"
  template:
    spec:
      fetch:
        - imgpkgBundle:
            image: public.ecr.aws/t0q8k6g2/prow-plugin/hook@sha256:632391aa30bbcbf20223c8678e712473f236df8c6740ea758fe7973ba8f084fd
      template:
        - ytt:
            paths:
              - config/
        - kbld:
            paths:
              - "-"
              - .imgpkg/images.yml
      deploy:
        - kapp: {}
